name: readit
description: A new Flutter project.
version: 1.1.0+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.4
  mobx: ^1.0.2+1
  flutter_mobx: ^1.0.1
  cupertino_icons: ^0.1.2
  google_fonts: ^0.3.7
  flutter_icons: ^1.0.0+1
  path_provider: ^1.6.0
  http: ^0.12.0+4
  objectdb: ^1.0.7+1
  cached_network_image: ^2.0.0
  uuid: ^2.0.4
  url_launcher: ^5.4.1
  validators: ^2.0.0+1
  flutter_html: ^0.11.1
  intl: ^0.16.1
  share: ^0.6.3+6
  shared_preferences: ^0.5.6+2
  shimmer: ^1.1.0
  path_provider_macos: ^0.0.4
  url_launcher_macos: ^0.0.1+4
  shared_preferences_macos: ^0.0.1+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
  build_runner: ^1.8.0
  mobx_codegen: ^1.0.2

flutter:
  uses-material-design: true

flutter_icons:
  image_path: assets/icon.png
  android: true
  ios: true
